ACTIVITY_LABELS = {
    1: "Sitting",
    2: "Standing",
    3: "Lying on Back",
    4: "Lying on Right Side",
    5: "Ascending Stairs",
    6: "Descending Stairs",
    7: "Standing in Elevator (Still)",
    8: "Moving in Elevator",
    9: "Walking in Parking Lot",
    10: "Walking on Treadmill (4 km/h, flat)",
    11: "Walking on Treadmill (4 km/h, 15° incline)",
    12: "Running on Treadmill (8 km/h)",
    13: "Exercising on Stepper",
    14: "Exercising on Cross Trainer",
    15: "Cycling on Exercise Bike (Horizontal)",
    16: "Cycling on Exercise Bike (Vertical)",
    17: "Rowing",
    18: "Jumping",
    19: "Playing Basketball",
}
WORKOUT_RECOMMENDATIONS = {
    1: {
        "recommendation": "You've been sitting — time to move! Try a light cardio session.",
        "exercises": ["Walking", "Stretching", "Bodyweight Squats", "Desk Exercises"],
        "duration_min": 20,
        "intensity": "Low",
    },
    2: {
        "recommendation": "Standing is good, but let's add some movement!",
        "exercises": ["Calf Raises", "Standing Leg Curls", "Marching in Place", "Side Lunges"],
        "duration_min": 15,
        "intensity": "Low",
    },
    3: {
        "recommendation": "Rest is important — when ready, try gentle mobility work.",
        "exercises": ["Cat-Cow Stretch", "Supine Twist", "Bridges", "Leg Raises"],
        "duration_min": 15,
        "intensity": "Low",
    },
    4: {
        "recommendation": "Recovery position detected — consider a gentle warm-up.",
        "exercises": ["Side-Lying Leg Lifts", "Hip Circles", "Gentle Stretching", "Deep Breathing"],
        "duration_min": 10,
        "intensity": "Low",
    },
    5: {
        "recommendation": "Great stair work! Build on this with a leg-focused session.",
        "exercises": ["Lunges", "Step-Ups", "Box Jumps", "Calf Raises", "Wall Sit"],
        "duration_min": 30,
        "intensity": "Medium",
    },
    6: {
        "recommendation": "Descending stairs works your quads — add some strength training!",
        "exercises": ["Squats", "Romanian Deadlifts", "Leg Press", "Bulgarian Split Squats"],
        "duration_min": 30,
        "intensity": "Medium",
    },
    7: {
        "recommendation": "Stationary time — try isometric exercises!",
        "exercises": ["Wall Sit", "Plank", "Isometric Holds", "Breathing Exercises"],
        "duration_min": 10,
        "intensity": "Low",
    },
    8: {
        "recommendation": "Brief movement detected — maintain momentum with a quick workout.",
        "exercises": ["Jumping Jacks", "High Knees", "Butt Kicks", "Arm Circles"],
        "duration_min": 15,
        "intensity": "Low",
    },
    9: {
        "recommendation": "Walking is a great base — increase intensity gradually.",
        "exercises": ["Brisk Walking", "Walking Lunges", "Power Walking", "Nordic Walking"],
        "duration_min": 30,
        "intensity": "Medium",
    },
    10: {
        "recommendation": "Flat treadmill walking — try adding incline or speed intervals.",
        "exercises": ["Incline Walking", "Interval Jogging", "Side Shuffles", "Walking Lunges"],
        "duration_min": 35,
        "intensity": "Medium",
    },
    11: {
        "recommendation": "Incline walking is excellent for glutes — keep pushing!",
        "exercises": ["Hill Sprints", "Stair Climber", "Glute Bridges", "Step-Ups"],
        "duration_min": 30,
        "intensity": "Medium",
    },
    12: {
        "recommendation": "Running detected — great cardio! Mix in interval training.",
        "exercises": ["Sprint Intervals", "Tempo Run", "Fartlek Training", "Cool-Down Jog"],
        "duration_min": 40,
        "intensity": "High",
    },
    13: {
        "recommendation": "Stepper workout — excellent for lower body endurance!",
        "exercises": ["Stepper Intervals", "Lunges", "Calf Raises", "Glute Kickbacks"],
        "duration_min": 35,
        "intensity": "Medium",
    },
    14: {
        "recommendation": "Cross trainer for full-body cardio — add resistance training!",
        "exercises": ["Cross Trainer HIIT", "Push-Ups", "Dumbbell Rows", "Core Work"],
        "duration_min": 40,
        "intensity": "Medium",
    },
    15: {
        "recommendation": "Horizontal cycling — great for recovery and endurance.",
        "exercises": ["Cycling Intervals", "Leg Extensions", "Hamstring Curls", "Hip Flexor Stretch"],
        "duration_min": 35,
        "intensity": "Medium",
    },
    16: {
        "recommendation": "Vertical cycling — more intense! Add upper body work.",
        "exercises": ["Spin Intervals", "Standing Pedaling", "Push-Ups", "Shoulder Press"],
        "duration_min": 40,
        "intensity": "High",
    },
    17: {
        "recommendation": "Rowing is a full-body exercise — complement with flexibility work.",
        "exercises": ["Rowing Intervals", "Deadlifts", "Lat Pulldowns", "Stretching"],
        "duration_min": 35,
        "intensity": "High",
    },
    18: {
        "recommendation": "Jumping — high impact! Build explosive power.",
        "exercises": ["Box Jumps", "Burpees", "Jump Squats", "Tuck Jumps", "Depth Jumps"],
        "duration_min": 25,
        "intensity": "High",
    },
    19: {
        "recommendation": "Basketball — excellent agility sport! Focus on court skills.",
        "exercises": ["Agility Ladder", "Defensive Slides", "Jump Shots", "Sprint Drills", "Court Sprints"],
        "duration_min": 45,
        "intensity": "High",
    },
}